export JOYSTICK_ID="1"
export JOYSTICK_RESOLUTION="32767"
export JOYSTICK_DEADZONE="1500"
export JOYSTICK_SENSITIVITY="100"

export PTU_SERIALPORT="/dev/ttyUSB0"
export PTU_BAUD_RATE="9600"
export PTU_MAX_PAN_RATE="100"
export PTU_MAX_TILT_RATE="100"
